"""initial

Revision ID: 2ce8841f0356
Revises: 
Create Date: 2026-06-03 02:15:13.664372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce8841f0356'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('fqdn', sa.String(), nullable=True),
    sa.Column('system_vendor', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('product_version', sa.String(), nullable=True),
    sa.Column('serial', sa.String(), nullable=True),
    sa.Column('form_factor', sa.String(), nullable=True),
    sa.Column('os_family', sa.String(), nullable=True),
    sa.Column('os_distribution', sa.String(), nullable=True),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('os_release', sa.String(), nullable=True),
    sa.Column('kernel', sa.String(), nullable=True),
    sa.Column('pkg_mgr', sa.String(), nullable=True),
    sa.Column('arch', sa.String(), nullable=True),
    sa.Column('cpu_model', sa.String(), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('cpu_threads', sa.Integer(), nullable=True),
    sa.Column('memory_mb', sa.Integer(), nullable=True),
    sa.Column('primary_ipv4', sa.String(), nullable=True),
    sa.Column('primary_interface', sa.String(), nullable=True),
    sa.Column('primary_mac', sa.String(), nullable=True),
    sa.Column('gateway', sa.String(), nullable=True),
    sa.Column('virt_type', sa.String(), nullable=True),
    sa.Column('virt_role', sa.String(), nullable=True),
    sa.Column('apparmor_status', sa.String(), nullable=True),
    sa.Column('selinux_status', sa.String(), nullable=True),
    sa.Column('fips', sa.Boolean(), nullable=True),
    sa.Column('bios_vendor', sa.String(), nullable=True),
    sa.Column('bios_version', sa.String(), nullable=True),
    sa.Column('bios_date', sa.String(), nullable=True),
    sa.Column('board_vendor', sa.String(), nullable=True),
    sa.Column('board_name', sa.String(), nullable=True),
    sa.Column('board_serial', sa.String(), nullable=True),
    sa.Column('service_mgr', sa.String(), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True),
    sa.Column('raw_facts', sa.JSON(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hosts_machine_id'), 'hosts', ['machine_id'], unique=True)
    op.create_table('import_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.Enum('CLI', 'WEB', name='importsource'), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('hosts_upserted', sa.Integer(), nullable=True),
    sa.Column('hosts_failed', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('k8s_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('host_tags',
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('host_id', 'tag_id')
    )
    op.create_table('k8s_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('CONTROL_PLANE', 'WORKER', 'ETCD', name='k8snoderole'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['k8s_clusters.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'cluster_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('k8s_nodes')
    op.drop_table('host_tags')
    op.drop_table('tags')
    op.drop_table('k8s_clusters')
    op.drop_table('import_logs')
    op.drop_index(op.f('ix_hosts_machine_id'), table_name='hosts')
    op.drop_table('hosts')
    # ### end Alembic commands ###
