"""add_k8s_namespace_and_import_log_k8s_cols

Revision ID: 361f830adeac
Revises: 2ce8841f0356
Create Date: 2026-06-03 06:49:41.448239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '361f830adeac'
down_revision: Union[str, Sequence[str], None] = '2ce8841f0356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('k8s_namespaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['k8s_clusters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'name')
    )
    op.add_column('import_logs', sa.Column('k8s_clusters_upserted', sa.Integer(), nullable=True))
    op.add_column('import_logs', sa.Column('k8s_nodes_upserted', sa.Integer(), nullable=True))
    op.add_column('import_logs', sa.Column('k8s_namespaces_upserted', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_logs', 'k8s_namespaces_upserted')
    op.drop_column('import_logs', 'k8s_nodes_upserted')
    op.drop_column('import_logs', 'k8s_clusters_upserted')
    op.drop_table('k8s_namespaces')
    # ### end Alembic commands ###
