"""add containers and host snapshots

Revision ID: 50f23d7d5a7c
Revises: 361f830adeac
Create Date: 2026-06-14 06:21:59.733555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f23d7d5a7c'
down_revision: Union[str, Sequence[str], None] = '361f830adeac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('ports', sa.String(), nullable=True),
    sa.Column('compose_project', sa.String(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'name')
    )
    op.create_table('host_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('import_log_id', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.ForeignKeyConstraint(['import_log_id'], ['import_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('import_logs', sa.Column('containers_upserted', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_logs', 'containers_upserted')
    op.drop_table('host_snapshots')
    op.drop_table('containers')
    # ### end Alembic commands ###
